version: '3.8'

services:
  blockchain0:
    container_name: "bulicoin-container0"
    build: ./
    environment:
    - PORT=5000
    - PORT_OUT=5000
    - NODE_NAME=RED
    ports:
      - 5000:5000
    volumes:
      - ./bulicoin_server:/bulicoin_server
    stdin_open: true
    tty: true

  blockchain1:
    container_name: "bulicoin-container1"
    build: ./
    environment:
    - PORT=5000
    - PORT_OUT=5001
    - NODE_NAME=GREEN
    ports:
      - 5001:5000
    volumes:
      - ./bulicoin_server:/bulicoin_server
    stdin_open: true
    tty: true

  blockchain2:
    container_name: "bulicoin-container2"
    build: ./
    environment:
    - PORT=5000
    - PORT_OUT=5002
    - NODE_NAME=BLUE
    ports:
      - 5002:5000
    volumes:
      - ./bulicoin_server:/bulicoin_server
    stdin_open: true
    tty: true

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "192.168.105.0/29"
          gateway: "192.168.105.1"